webSite/goods/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *
urlpatterns =[


    url(r'^category/(?P<url>\w+)/$', topcategory,name='topcategory'),
    url(r'^category/(?P<url>\w+)/(?P<idtop>\w+)/$', category,name='category'),
    url(r'^card/(?P<urlcat>\w+)/(?P<urlgood>\w+)/$', cardGood,name='cardgood'),
    url(r'^cart/$',cart,name='cart'),

    url(r'^$',mainPage),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webSite/userdate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# -*- coding: utf-8 -*-
from .views import *

urlpatterns = [

    url(r'^$', profile, name='profile'),
    url(r'^login/$', LogIn,name='LogIn'),
    url(r'^logout/$', LogOut,name='LogOut'),
    url(r'^registration/$',registr,name="registration")
]

webSite/webSite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# -*- coding: utf-8 -*-
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("userdate.urls",namespace="userdate")),
    url(r'^', include("goods.urls",namespace="goods")),

]

webSite/userdate/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
# Create your models here.
from django.utils.encoding import python_2_unicode_compatible
@python_2_unicode_compatible
class UserInformations(models.Model):
    class Meta():
        verbose_name="Информация о пользователе"
    userId=models.ForeignKey(User)
    name=models.CharField(max_length=25,verbose_name="Имя")
    lastname=models.CharField(max_length=25,verbose_name="Фамилия")
    phonenumber=models.CharField(max_length=13,verbose_name="Телефон")
    email=models.EmailField(verbose_name="Email")

    def __str__(self):
        return self.email +" "+self.lastname

webSite/userdate/forms.py
# -*- coding: utf-8 -*-
from django import forms

# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
class RegistrationForm(forms.Form):
        name=forms.CharField(label="Имя",max_length=25)
        lastname=forms.CharField(label="Фамилия",max_length=25)
        phonenumber=forms.CharField(label="Телефон",min_length=13,max_length=13,widget=forms.TextInput(
            attrs={
                'type':'text',
                'placeholder':'** *** ********',

            }
        ))
        email=forms.EmailField()
        password = forms.CharField(label="Пароль", widget=forms.PasswordInput(),max_length=15,min_length=6)
        passwordreapit = forms.CharField(label="Пароль повторно", widget=forms.PasswordInput(),max_length=15,min_length=6)






        def clead_phonenumber(self):
            date=self.changed_data['phonenumber']
            if int(date):
                raise  forms.ValidationError("Только числа")
            return date

        def clean(self):
            cleaned_date=super(RegistrationForm,self).clean()
            password=cleaned_date.get('password')
            passwordreapit=cleaned_date.get('passwordreapit')

            if password!=passwordreapit:
                self.add_error("password","Пароли не совпадают")


class LoginForm(forms.Form):
    email=forms.EmailField()
    password=forms.CharField(label="Пароль", widget=forms.PasswordInput(),max_length=15, min_length=6)

webSite/userdate/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render_to_response, redirect,render
from django.template.context_processors import csrf

from .forms import *

from .models import UserInformations
# Create your views here.


def profile(request):
    args={}
    args.update(csrf(request))
    user=User.objects.get(username=request.user.username)
    args['email'] = user.email
    args['fname'] = user.first_name
    args['lname'] = user.last_name

    return render(request,"profile.html",args)

def LogIn(request):
    args = {}
    args.update(csrf(request))

    if request.user.is_authenticated:

        return render_to_response("home.html",args)

    logout(request)
    if request.method=="POST":
        form=LoginForm(request.POST)
        if form.is_valid():
            user=authenticate(username=form.cleaned_data['email'],password=form.cleaned_data['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                else:
                    args['error'] = "Данный пользователь не активен"
                return redirect("/")
            else:
                args['error']="Проверте правильность введенных данных"
                args['form'] = form
                return render(request, "login.html",args)
    else:
        form= LoginForm()
    args['form'] = form

    return render(request, "login.html", args)

def LogOut(request):
    logout(request)
    return render(request, "home.html")



def registr(request):
    if request.user.is_authenticated:
        return redirect('/')
    args = {}
    args.update(csrf(request))
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            lastname = form.cleaned_data['lastname']
            phonenumber = form.cleaned_data['phonenumber']
            user = User.objects.create_user(email, email, password)
            user.first_name = name
            user.last_name = lastname
            user.save()
            userInfo = UserInformations.objects.create(
                userId=user,
                name=name,
                lastname=lastname,
                phonenumber=phonenumber,
                email=email)
            userInfo.save()

            if user:
                return redirect('/')


    else:
        form = RegistrationForm()
    args['form'] = form
    return render(request, "registration.html", args)

webSite/userdate/templates/login.html
{% extends 'base.html' %}
{% block content %}
      <h3>Авторизация пользователя</h3>
        <div class="userAuth">
    {{ error }}
    <form method="post" action="{% url 'userdate:LogIn' %}">
    {% csrf_token %}
        {% for field in form %}
                <label id="{{ field.id_for_label }}">{{ field.label }}:</label><br>
               {{ field.as_widget }}<br>
                {% for error in field.errors %}
                   <p class="error">{{ error }}</p>
                    {% endfor %}
            {% endfor %}
    <input type="submit" value="Войти">
    </form>
        </div>
{% endblock %}

webSite/userdate/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <div>
    <h3>Информация о пользователе:</h3>
    <p> Email: {{ email }}</p>
     <p> Имя: {{ fname }}</p>
     <p> Фамилия: {{ lname}}</p>
        </div>
    <hr>
    <div class="">
    <h3>Ваши заказы:</h3>
    </div>
{% endblock %}

webSite/userdate/templates/registration.html
{% extends 'base.html' %}
{% block content %}

    <h3>Регистрация нового пользователя</h3>
    <div class="userAuth">
        <form action="{% url 'userdate:registration'%}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <label id="{{ field.id_for_label }}">{{ field.label }}:</label><br>
               {{ field.as_widget }}<br>
                {% for error in field.errors %}
                   <p class="error">{{ error }}</p>
                    {% endfor %}
            {% endfor %}
            <input type="submit" value="Log in">
        </form>
    </div>
{% endblock %}