webSite/goods/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *
urlpatterns =[


    url(r'^category/(?P<url>\w+)/$', topcategory,name='topcategory'),
    url(r'^category/(?P<url>\w+)/(?P<idtop>\w+)/$', category,name='category'),
    url(r'^card/(?P<urlcat>\w+)/(?P<urlgood>\w+)/$', cardGood,name='cardgood'),
    url(r'^cart/$',cart,name='cart'),

    url(r'^$',mainPage),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webSite/userdate/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# -*- coding: utf-8 -*-
from .views import *

urlpatterns = [

    url(r'^$', profile, name='profile'),
    url(r'^login/$', LogIn,name='LogIn'),
    url(r'^logout/$', LogOut,name='LogOut'),
    url(r'^registration/$',registr,name="registration")
]

webSite/webSite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# -*- coding: utf-8 -*-
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("userdate.urls",namespace="userdate")),
    url(r'^', include("goods.urls",namespace="goods")),

]

webSite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load goods_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="page">
    <header>
            {% header request %}
    </header>
    <div class="middle">
        <div class="menu">

            {% side_menu %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
    <footer>

    </footer>
</body>
</html>

webSite/templates/cartPage.html
{% extends "base.html" %}
{% block content %}
    this page is a cart
{% endblock %}

webSite/templates/header.html
<div class="head">
    <a href="/"><div class="logo">
{{ qwe }}
    </div></a>
{% load userdatetags %}
    <div class="login">
       {% if request.user.is_authenticated %}
           Hello, <a href="{%  url 'userdate:profile' %}">{{ request.user.username }}</a>.
            <a href="{% url 'userdate:LogOut' %}">Выйти</a>
           {% else %}
           <a href="{% url 'userdate:LogIn' %}"> Войти</a>
       {% endif %}
    </div>
    <div class="cart"><a href="{% url 'goods:cart' %}">Корзина</a></div>
</div>